version: '3'
services:
  web:
    image: nginx:alpine
    volumes:
      - "./web/settings/default.conf:/etc/nginx/conf.d/default.conf"
      - "./web/settings/nginx.conf:/etc/nginx/nginx.conf"
      - "./project/html:/var/www/html"
      - "./web/logs:/var/log/nginx"
    ports:
      - "8080:80"
    restart: always
    depends_on:
      - php
      - mysql
      - redis
  php:
    build: ./php
    volumes:
      - "./project/html:/var/www/html"
    restart: always
  mysql:
    image: mysql:8.0
    ports:
      - "13306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: p@ssw0rd
      MYSQL_DATABASE: test
      MYSQL_USER: dev
      MYSQL_PASSWORD: dev
      TZ: Asia/Tokyo
    volumes:
      - "./mysql/mount:/var/lib/mysql"
      - "./mysql/settings/my.cnf:/etc/mysql/conf.d/my.cnf"
      - "./mysql/dump/setup.sql:/docker-entrypoint-initdb.d/dump.sql"
      - "./mysql/logs:/var/log/mysql"
    restart: always
  redis:
    image: redis:alpine
    ports:
      - "16379:6379"
    volumes:
      - "./redis/mount:/data"
